import type { RecommendationResource } from "./types";

export const DEMO_PRIMARY_GOAL_IDS = ["programming"];
export const DEMO_TOPICS = [
  { id: "workout", label: "Workout", detail: "Movement & energy", progress: 42 },
  { id: "java", label: "Java & programming", detail: "Build technical depth", progress: 28 },
  { id: "ai", label: "AI learning", detail: "Understand what is next", progress: 16 },
  { id: "career", label: "Career & product", detail: "Make ideas actionable", progress: 64 },
] as const;

export function createDemoResources(nowInput: string): RecommendationResource[] {
  const now = new Date(nowInput);

  return [
    {
      id: "demo-fitness-reel",
      url: "https://www.instagram.com/reels/",
      source: "instagram",
      contentType: "short_video",
      title: "A better shoulder warm-up",
      estimatedMinutes: 1,
      cognitiveEffort: 0.15,
      actionability: 0.95,
      timeSensitivity: 0.15,
      savedAt: daysAgo(now, 18),
      status: "active",
      goalMatches: [{ goalId: "fitness", relevance: 0.92 }],
      section: "Build a sustainable practice",
      objective: "Build a repeatable movement habit.",
      topic: "workout",
    },
    {
      id: "demo-oauth-short",
      url: "https://www.youtube.com/shorts/",
      source: "youtube",
      contentType: "short_video",
      title: "OAuth in sixty seconds",
      estimatedMinutes: 1,
      cognitiveEffort: 0.3,
      actionability: 0.62,
      timeSensitivity: 0.1,
      savedAt: daysAgo(now, 7),
      status: "active",
      goalMatches: [{ goalId: "programming", relevance: 0.82 }],
      section: "Understand the foundations",
      objective: "Explain the building blocks before going deeper.",
      topic: "java",
    },
    {
      id: "demo-oauth-video",
      url: "https://www.youtube.com/results?search_query=oauth+explained+visually",
      source: "youtube",
      contentType: "video",
      title: "Understanding OAuth visually",
      estimatedMinutes: 8,
      cognitiveEffort: 0.72,
      actionability: 0.83,
      timeSensitivity: 0.15,
      savedAt: daysAgo(now, 35),
      status: "active",
      goalMatches: [{ goalId: "programming", relevance: 0.96 }],
      section: "Understand the foundations",
      objective: "Explain the building blocks before going deeper.",
      topic: "java",
    },
    {
      id: "demo-technical-article",
      url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Authentication",
      source: "web",
      contentType: "article",
      title: "Authentication architecture notes",
      estimatedMinutes: 15,
      cognitiveEffort: 0.9,
      actionability: 0.82,
      timeSensitivity: 0.2,
      savedAt: daysAgo(now, 52),
      status: "active",
      goalMatches: [{ goalId: "programming", relevance: 0.94 }],
      section: "Build something useful",
      objective: "Turn theory into a practical implementation.",
      topic: "ai",
    },
    {
      id: "demo-hackathon-deadline",
      url: "https://example.com/hackathon-submission",
      source: "web",
      contentType: "article",
      title: "Hackathon submission checklist",
      estimatedMinutes: 4,
      cognitiveEffort: 0.55,
      actionability: 0.96,
      timeSensitivity: 0.82,
      timeSensitivityReason: "The submission deadline is approaching",
      relevantUntil: daysFromNow(now, 2),
      savedAt: daysAgo(now, 3),
      status: "active",
      goalMatches: [{ goalId: "programming", relevance: 0.86 }],
      section: "Build something useful",
      objective: "Turn theory into a practical implementation.",
      topic: "ai",
    },
    {
      id: "demo-career-newsletter",
      url: "https://example.com/product-newsletter",
      source: "newsletter",
      contentType: "newsletter",
      title: "The product idea validation issue",
      estimatedMinutes: 5,
      cognitiveEffort: 0.45,
      actionability: 0.74,
      timeSensitivity: 0.35,
      savedAt: daysAgo(now, 94),
      status: "active",
      goalMatches: [{ goalId: "career", relevance: 0.76 }],
      section: "Make ideas actionable",
      objective: "Convert saved inspiration into a next step.",
      topic: "career",
    },
    {
      id: "demo-product-discovery",
      url: "https://example.com/product-discovery",
      source: "newsletter",
      contentType: "article",
      title: "A lightweight product discovery loop",
      estimatedMinutes: 7,
      cognitiveEffort: 0.62,
      actionability: 0.9,
      timeSensitivity: 0.25,
      savedAt: daysAgo(now, 21),
      status: "active",
      goalMatches: [{ goalId: "career", relevance: 0.84 }],
      section: "Make ideas actionable",
      objective: "Convert saved inspiration into a next step.",
      topic: "career",
    },
    {
      id: "demo-focus-reset",
      url: "https://example.com/focus-reset",
      source: "reddit",
      contentType: "article",
      title: "The two-minute focus reset",
      estimatedMinutes: 2,
      cognitiveEffort: 0.2,
      actionability: 0.88,
      timeSensitivity: 0.1,
      savedAt: daysAgo(now, 12),
      status: "active",
      goalMatches: [{ goalId: "fitness", relevance: 0.48 }],
      section: "Build a sustainable practice",
      objective: "Build a repeatable movement habit.",
      topic: "workout",
    },
    {
      id: "demo-api-design",
      url: "https://example.com/api-design",
      source: "reddit",
      contentType: "article",
      title: "API design decisions that age well",
      estimatedMinutes: 10,
      cognitiveEffort: 0.8,
      actionability: 0.78,
      timeSensitivity: 0.15,
      savedAt: daysAgo(now, 44),
      status: "active",
      goalMatches: [{ goalId: "programming", relevance: 0.9 }],
      section: "Build something useful",
      objective: "Turn theory into a practical implementation.",
      topic: "java",
    },
    {
      id: "demo-debugging",
      url: "https://www.youtube.com/results?search_query=debugging+habits",
      source: "youtube",
      contentType: "video",
      title: "A calmer way to debug",
      estimatedMinutes: 6,
      cognitiveEffort: 0.58,
      actionability: 0.86,
      timeSensitivity: 0.1,
      savedAt: daysAgo(now, 30),
      status: "active",
      goalMatches: [{ goalId: "programming", relevance: 0.88 }],
      section: "Build something useful",
      objective: "Turn theory into a practical implementation.",
      topic: "ai",
    },
    {
      id: "demo-learning-notes",
      url: "https://example.com/learning-notes",
      source: "web",
      contentType: "article",
      title: "How to make notes you revisit",
      estimatedMinutes: 5,
      cognitiveEffort: 0.42,
      actionability: 0.83,
      timeSensitivity: 0.1,
      savedAt: daysAgo(now, 66),
      status: "active",
      goalMatches: [{ goalId: "career", relevance: 0.72 }],
      section: "Make ideas actionable",
      objective: "Convert saved inspiration into a next step.",
      topic: "career",
    },
  ];
}

function daysAgo(now: Date, days: number): string {
  return new Date(now.getTime() - days * 86_400_000).toISOString();
}

function daysFromNow(now: Date, days: number): string {
  return new Date(now.getTime() + days * 86_400_000).toISOString();
}
